classDiagram

    class UserPut {
        <<HttpRequest>>
        string FirstName
        string LastName
    }

    class IssuePut {
        <<HttpRequest>>
        string Label
    }

    class CommentPut {
        <<HttpRequest>>
        string Text
    }