classDiagram

    direction BT

    note for ResourcePut "<b>Fields you can override later</b>"
    note for ResourcePost "<b>Fields you can set initially</b><br/><br/>(includes the fields you<br/>can override later)"
    note for ResourceGet "<b>Fields you can read</b><br/><br/>(includes the fields you<br/>can set initially and<br/>override later)"

    class ResourceGet {
        <<HttpResponse>>
        ...
    }
    class ResourcePost {
        <<HttpRequest>>
        ...
    }
    class ResourcePut {
        <<HttpRequest>>
        ...
    }

    ResourceGet --|> ResourcePost
    ResourcePost --|> ResourcePut

    style ResourceGet fill:yellow
    style ResourcePost fill:yellow
    style ResourcePut fill:yellow