classDiagram

    class UserQuery {
        <<HttpRequestQuery>>
    }

    class IssueQuery {
        <<HttpRequestQuery>>
    }

    class CommentQuery {
        <<HttpRequestQuery>>
        string IssueId
    }