classDiagram

    direction RL

    class ResourceQuery {
        <<HttpRequestQuery>>
        ...
    }

    note for ResourceQuery "Parameters for querying<br/>a specific type of<br/>resource"

    style ResourceQuery fill:yellow